name: Release

on:
  push:
    branches:
      - master
    paths:
      - action.yml
      - action.js
      - package.json

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: compute_tag
        uses: ./
        with:
          github_token: ${{ github.token }}
          version_scheme: continuous
          version_type: prerelease

      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          release_name: ${{ steps.compute_tag.outputs.next_tag }}
          body: >
            Automatic release of ${{ steps.compute_tag.outputs.next_tag }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
